{% set name = "dremio-arrow" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 16298472d5e43b52d7f419d24476403d265d7fde0b5f487066ed784ce35fe52c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
    - poetry >=1.1.15
  run:
    - python >=3.7,<3.11
    - pandas >=1.3,<=1.4
    - pyarrow >=4.0,<=9.0

test:
  imports:
    - dremioarrow

about:
  home: https://github.com/jaysnm/dremio-arrow
  summary: Dremio SQL Lakehouse Arrow Flight Client.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
